package quebracabeca;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.List;

public class Design extends javax.swing.JFrame{
    
    QuebraCabeca puzzle = new QuebraCabeca();
    Color cor = new Color(240, 200, 8);
    
    public Design(){
        initComponents();
        this.setResizable(false);
        this.getContentPane().setBackground(cor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bum = new javax.swing.JButton();
        bdois = new javax.swing.JButton();
        btres = new javax.swing.JButton();
        bquatro = new javax.swing.JButton();
        bcinco = new javax.swing.JButton();
        bseis = new javax.swing.JButton();
        bsete = new javax.swing.JButton();
        boito = new javax.swing.JButton();
        bnove = new javax.swing.JButton();
        bdez = new javax.swing.JButton();
        bonze = new javax.swing.JButton();
        bdoze = new javax.swing.JButton();
        btreze = new javax.swing.JButton();
        bquatorze = new javax.swing.JButton();
        bquinze = new javax.swing.JButton();
        bdezesseis = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jogadas = new javax.swing.JLabel();
        temporizador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bum.setText("1");
        bum.setName("bum"); // NOI18N
        bum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bumActionPerformed(evt);
            }
        });

        bdois.setText("2");
        bdois.setName("bdois"); // NOI18N
        bdois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdoisActionPerformed(evt);
            }
        });

        btres.setText("3");
        btres.setName("btres"); // NOI18N
        btres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresActionPerformed(evt);
            }
        });

        bquatro.setText("4");
        bquatro.setName("bquatro"); // NOI18N
        bquatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquatroActionPerformed(evt);
            }
        });

        bcinco.setText("5");
        bcinco.setName("bcinco"); // NOI18N
        bcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcincoActionPerformed(evt);
            }
        });

        bseis.setText("6");
        bseis.setName("bseis"); // NOI18N
        bseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bseisActionPerformed(evt);
            }
        });

        bsete.setText("7");
        bsete.setName("bsete"); // NOI18N
        bsete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bseteActionPerformed(evt);
            }
        });

        boito.setText("8");
        boito.setName("boito"); // NOI18N
        boito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boitoActionPerformed(evt);
            }
        });

        bnove.setText("9");
        bnove.setName("bnove"); // NOI18N
        bnove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnoveActionPerformed(evt);
            }
        });

        bdez.setText("10");
        bdez.setName("bdez"); // NOI18N
        bdez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdezActionPerformed(evt);
            }
        });

        bonze.setText("11");
        bonze.setName("bonze"); // NOI18N
        bonze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonzeActionPerformed(evt);
            }
        });

        bdoze.setText("12");
        bdoze.setName("bdoze"); // NOI18N
        bdoze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdozeActionPerformed(evt);
            }
        });

        btreze.setText("13");
        btreze.setName("btreze"); // NOI18N
        btreze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrezeActionPerformed(evt);
            }
        });

        bquatorze.setText("14");
        bquatorze.setName("bquatorze"); // NOI18N
        bquatorze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquatorzeActionPerformed(evt);
            }
        });

        bquinze.setText("15");
        bquinze.setName("bquinze"); // NOI18N
        bquinze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquinzeActionPerformed(evt);
            }
        });

        bdezesseis.setName("bdezesseis"); // NOI18N
        bdezesseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdezesseisActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titulo.setText("<html><b>Quebra Cabeça</b></html>");
        titulo.setAlignmentX(0.5F);
        titulo.setName("titulo"); // NOI18N

        jogadas.setText("Jogadas: 0");
        jogadas.setName("jogadas"); // NOI18N

        temporizador.setText("Tempo: 00:00:00");
        temporizador.setName("temporizador"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jogadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(temporizador))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btreze, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bnove, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bcinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bdois, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bseis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bdez, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(bquatorze, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bsete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bonze, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(bquinze, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bquatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bdoze, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(bdezesseis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jogadas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(temporizador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bquatro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bcinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bseis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boito, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bnove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bonze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdoze, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btreze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bquatorze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bquinze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdezesseis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void bumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bumActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bum, bdois, bcinco, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bumActionPerformed

    private void bdoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdoisActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bdois, bum, btres, bseis, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bdoisActionPerformed

    private void btresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(btres, bdois, bquatro, bsete, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_btresActionPerformed

    private void bquatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquatroActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bquatro, btres, boito, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bquatroActionPerformed

    private void bcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcincoActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bcinco, bum, bseis, bnove, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bcincoActionPerformed

    private void bseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bseisActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bseis, bcinco, bdois, bsete, bdez, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bseisActionPerformed

    private void bseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bseteActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bsete, btres, bseis, boito, bonze, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bseteActionPerformed

    private void boitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boitoActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(boito, bquatro, bsete, bdoze, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_boitoActionPerformed

    private void bnoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnoveActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bnove, bcinco, bdez, btreze, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bnoveActionPerformed

    private void bdezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdezActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bdez, bseis, bnove, bonze, bquatorze, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bdezActionPerformed

    private void bonzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonzeActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bonze, bsete, bdez, bdoze, bquinze, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bonzeActionPerformed

    private void bdozeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdozeActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bdoze, boito, bonze, bdezesseis, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bdozeActionPerformed

    private void btrezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrezeActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(btreze, bnove, bquatorze, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_btrezeActionPerformed

    private void bquatorzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquatorzeActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bquatorze, bdez, btreze, bquinze, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bquatorzeActionPerformed

    private void bquinzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquinzeActionPerformed
        // TODO add your handling code here:
        puzzle.mudar(bquinze, bonze, bquatorze, bdezesseis, temporizador);
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
    }//GEN-LAST:event_bquinzeActionPerformed

    private void bdezesseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdezesseisActionPerformed
        // TODO add your handling code here:
        boolean aux;
        int aux2;
        List vetor = new ArrayList();

        puzzle.mudar(bdezesseis, bdoze, bquinze, temporizador);
        
        jogadas.setText("Jogadas: " + puzzle.getJogadas());
        
        if(bdezesseis.getText().equals("")){
            vetor.add(bum.getText());
            vetor.add( bdois.getText());
            vetor.add( btres.getText());
            vetor.add( bquatro.getText());
            vetor.add( bcinco.getText());
            vetor.add( bseis.getText());
            vetor.add( bsete.getText());
            vetor.add( boito.getText());
            vetor.add( bnove.getText());
            vetor.add( bdez.getText());
            vetor.add( bonze.getText());
            vetor.add( bdoze.getText());
            vetor.add( btreze.getText());
            vetor.add( bquatorze.getText());
            vetor.add( bquinze.getText());
            vetor.add(bdezesseis.getText());
            
            aux = puzzle.win(vetor);
        
            if(aux == true){
                puzzle.pararTemp();
                JOptionPane.showMessageDialog(null, "Você Venceu! Parabéns!", "Vencedor", 1);
                aux2 = JOptionPane.showConfirmDialog(null, "Deseja jogar novamente?", "Jogar novamente!", 1);
                if(aux2 == 0) {
                    temporizador.setText("Tempo: 00:00:00");
                    puzzle.setJogadas(0);
                    jogadas.setText("Jogadas: " + puzzle.getJogadas());
                    puzzle.embaralhar(vetor);
                    bum.setText(vetor.get(0).toString());
                    bdois.setText(vetor.get(1).toString());
                    btres.setText(vetor.get(2).toString());
                    bquatro.setText(vetor.get(3).toString());
                    bcinco.setText(vetor.get(4).toString());
                    bseis.setText(vetor.get(5).toString());
                    bsete.setText(vetor.get(6).toString());
                    boito.setText(vetor.get(7).toString());
                    bnove.setText(vetor.get(8).toString());
                    bdez.setText(vetor.get(9).toString());
                    bonze.setText(vetor.get(10).toString());
                    bdoze.setText(vetor.get(11).toString());
                    btreze.setText(vetor.get(12).toString());
                    bquatorze.setText(vetor.get(13).toString());
                    bquinze.setText(vetor.get(14).toString());
                    bdezesseis.setText(vetor.get(15).toString());
                }else{
                    JOptionPane.showMessageDialog(null, "Obrigado por jogar!", "Fim do jogo", 1);
                    System.exit(0);
                }

            }
        }

    }//GEN-LAST:event_bdezesseisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design().setVisible(true);
            }
        });

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcinco;
    private javax.swing.JButton bdez;
    private javax.swing.JButton bdezesseis;
    private javax.swing.JButton bdois;
    private javax.swing.JButton bdoze;
    private javax.swing.JButton bnove;
    private javax.swing.JButton boito;
    private javax.swing.JButton bonze;
    private javax.swing.JButton bquatorze;
    private javax.swing.JButton bquatro;
    private javax.swing.JButton bquinze;
    private javax.swing.JButton bseis;
    private javax.swing.JButton bsete;
    private javax.swing.JButton btres;
    private javax.swing.JButton btreze;
    private javax.swing.JButton bum;
    private javax.swing.JLabel jogadas;
    private javax.swing.JLabel temporizador;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}